name: build
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        theme: [tailwind, one-dark-pro]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%y%m%d%H%M)" >> $GITHUB_ENV

      - name: Compile PDF
        run: |
          typst compile main.typ --font-path ./fonts \
            --input theme=${{ matrix.theme }} \
            --format pdf "椭圆曲线-数论与密码学-第二版-${{ env.DATE }}.pdf"

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF-${{ matrix.theme }}-${{ env.DATE }}
          path: 椭圆曲线-数论与密码学-第二版-${{ env.DATE }}.pdf

      - name: Release (if tag)
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          name: '${{ github.ref_name }}'
          files: 椭圆曲线-数论与密码学-第二版-${{ env.DATE }}.pdf
