name: build
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        theme: [tailwind, one-dark-pro]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Compile PDF
        run: |
          typst compile main.typ --font-path ./fonts \
            --input theme=${{ matrix.theme }} \
            --format pdf main-${{ matrix.theme }}.pdf

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: main-${{ matrix.theme }}
          path: main-${{ matrix.theme }}.pdf

  release:
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    steps:
      - name: Download all PDFs
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: '${{ github.ref_name }} — ${{ env.DATE }}'
          files: artifacts/**/*.pdf
