name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        theme: [tailwind, one-dark-pro]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Typst
        uses: typst-community/setup-typst@v5

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%y%m%d%H%M)" >> $GITHUB_ENV

      - name: Compile PDF
        run: |
          typst compile main.typ --font-path ./fonts \
            --input theme=${{ matrix.theme }} \
            --format pdf "main-${{ matrix.theme }}-${{ env.DATE }}.pdf"

      - name: Upload PDF file
        uses: actions/upload-artifact@v7
        with:
          path: 'main-${{ matrix.theme }}-${{ env.DATE }}.pdf'
          archive: false
