name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        theme: [tailwind, one-dark-pro]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Compile PDF
        run: |
          typst compile main.typ --font-path ./fonts \
            --input theme=${{ matrix.theme }} \
            --format pdf "Elliptic-Curves-Number-Theory-and-Cryptography-${{ matrix.theme }}.pdf"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: '**/*.pdf'
